// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getHorizonExample = `-- name: GetHorizonExample :one

SELECT id, created_at FROM horizon_example LIMIT 1
`

// Queries for horizon
func (q *Queries) GetHorizonExample(ctx context.Context) (HorizonExample, error) {
	row := q.db.QueryRow(ctx, getHorizonExample)
	var i HorizonExample
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
