// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getRadarExample = `-- name: GetRadarExample :one

SELECT id, created_at FROM radar_example LIMIT 1
`

// Queries for radar
func (q *Queries) GetRadarExample(ctx context.Context) (RadarExample, error) {
	row := q.db.QueryRow(ctx, getRadarExample)
	var i RadarExample
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
