// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getReflexExample = `-- name: GetReflexExample :one

SELECT id, created_at FROM reflex_example LIMIT 1
`

// Queries for reflex
func (q *Queries) GetReflexExample(ctx context.Context) (ReflexExample, error) {
	row := q.db.QueryRow(ctx, getReflexExample)
	var i ReflexExample
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
