// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getGuardExample = `-- name: GetGuardExample :one

SELECT id, created_at FROM guard_example LIMIT 1
`

// Queries for guard
func (q *Queries) GetGuardExample(ctx context.Context) (GuardExample, error) {
	row := q.db.QueryRow(ctx, getGuardExample)
	var i GuardExample
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
