// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Queries for pulse
	GetPulseExample(ctx context.Context) (PulseExample, error)
}

var _ Querier = (*Queries)(nil)
