// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getPulseExample = `-- name: GetPulseExample :one

SELECT id, created_at FROM pulse_example LIMIT 1
`

// Queries for pulse
func (q *Queries) GetPulseExample(ctx context.Context) (PulseExample, error) {
	row := q.db.QueryRow(ctx, getPulseExample)
	var i PulseExample
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
