// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getNexusExample = `-- name: GetNexusExample :one

SELECT id, created_at FROM nexus_example LIMIT 1
`

// Queries for nexus
func (q *Queries) GetNexusExample(ctx context.Context) (NexusExample, error) {
	row := q.db.QueryRow(ctx, getNexusExample)
	var i NexusExample
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
