// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Queries for pilot
	GetPilotExample(ctx context.Context) (PilotExample, error)
}

var _ Querier = (*Queries)(nil)
