// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Queries for radar
	GetRadarExample(ctx context.Context) (RadarExample, error)
}

var _ Querier = (*Queries)(nil)
