// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getPilotExample = `-- name: GetPilotExample :one

SELECT id, created_at FROM pilot_example LIMIT 1
`

// Queries for pilot
func (q *Queries) GetPilotExample(ctx context.Context) (PilotExample, error) {
	row := q.db.QueryRow(ctx, getPilotExample)
	var i PilotExample
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
