// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getControlExample = `-- name: GetControlExample :one

SELECT id, created_at FROM control_example LIMIT 1
`

// Queries for control
func (q *Queries) GetControlExample(ctx context.Context) (ControlExample, error) {
	row := q.db.QueryRow(ctx, getControlExample)
	var i ControlExample
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
