// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getProbeExample = `-- name: GetProbeExample :one

SELECT id, created_at FROM probe_example LIMIT 1
`

// Queries for probe
func (q *Queries) GetProbeExample(ctx context.Context) (ProbeExample, error) {
	row := q.db.QueryRow(ctx, getProbeExample)
	var i ProbeExample
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
