// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getSignalExample = `-- name: GetSignalExample :one

SELECT id, created_at FROM signal_example LIMIT 1
`

// Queries for signal
func (q *Queries) GetSignalExample(ctx context.Context) (SignalExample, error) {
	row := q.db.QueryRow(ctx, getSignalExample)
	var i SignalExample
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
