// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getGridExample = `-- name: GetGridExample :one

SELECT id, created_at FROM grid_example LIMIT 1
`

// Queries for grid
func (q *Queries) GetGridExample(ctx context.Context) (GridExample, error) {
	row := q.db.QueryRow(ctx, getGridExample)
	var i GridExample
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
