// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getMindExample = `-- name: GetMindExample :one

SELECT id, created_at FROM mind_example LIMIT 1
`

// Queries for mind
func (q *Queries) GetMindExample(ctx context.Context) (MindExample, error) {
	row := q.db.QueryRow(ctx, getMindExample)
	var i MindExample
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
