// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Queries for optic
	GetOpticExample(ctx context.Context) (OpticExample, error)
}

var _ Querier = (*Queries)(nil)
