// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getOpticExample = `-- name: GetOpticExample :one

SELECT id, created_at FROM optic_example LIMIT 1
`

// Queries for optic
func (q *Queries) GetOpticExample(ctx context.Context) (OpticExample, error) {
	row := q.db.QueryRow(ctx, getOpticExample)
	var i OpticExample
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
