// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID             pgtype.UUID        `json:"id"`
	AgentKeyHash   string             `json:"agent_key_hash"`
	Name           string             `json:"name"`
	Hostname       pgtype.Text        `json:"hostname"`
	IpAddress      *netip.Addr        `json:"ip_address"`
	OsType         string             `json:"os_type"`
	OsVersion      pgtype.Text        `json:"os_version"`
	Arch           pgtype.Text        `json:"arch"`
	Version        string             `json:"version"`
	Capabilities   []byte             `json:"capabilities"`
	Status         string             `json:"status"`
	LastHeartbeat  pgtype.Timestamptz `json:"last_heartbeat"`
	RegisteredAt   pgtype.Timestamptz `json:"registered_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Metadata       []byte             `json:"metadata"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Tags           []string           `json:"tags"`
}

type AgentConfig struct {
	ID          pgtype.UUID        `json:"id"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	ConfigKey   string             `json:"config_key"`
	ConfigValue []byte             `json:"config_value"`
	Version     pgtype.Int4        `json:"version"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AgentDatum struct {
	ID             pgtype.UUID        `json:"id"`
	AgentID        pgtype.UUID        `json:"agent_id"`
	DataType       string             `json:"data_type"`
	Payload        []byte             `json:"payload"`
	CollectedAt    pgtype.Timestamptz `json:"collected_at"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Tags           []string           `json:"tags"`
	Metadata       []byte             `json:"metadata"`
}

type AgentGroup struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AgentGroupMember struct {
	AgentID  pgtype.UUID        `json:"agent_id"`
	GroupID  pgtype.UUID        `json:"group_id"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type AgentHealth struct {
	ID             pgtype.UUID        `json:"id"`
	AgentID        pgtype.UUID        `json:"agent_id"`
	CpuUsage       pgtype.Numeric     `json:"cpu_usage"`
	MemoryUsage    pgtype.Numeric     `json:"memory_usage"`
	DiskUsage      pgtype.Numeric     `json:"disk_usage"`
	NetworkIn      pgtype.Int8        `json:"network_in"`
	NetworkOut     pgtype.Int8        `json:"network_out"`
	ProcessesCount pgtype.Int4        `json:"processes_count"`
	UptimeSeconds  pgtype.Int8        `json:"uptime_seconds"`
	RecordedAt     pgtype.Timestamptz `json:"recorded_at"`
}

type AgentLog struct {
	ID         pgtype.UUID        `json:"id"`
	AgentID    pgtype.UUID        `json:"agent_id"`
	Level      string             `json:"level"`
	Message    string             `json:"message"`
	Source     pgtype.Text        `json:"source"`
	Metadata   []byte             `json:"metadata"`
	RecordedAt pgtype.Timestamptz `json:"recorded_at"`
}

type AgentSecret struct {
	ID             pgtype.UUID        `json:"id"`
	AgentID        pgtype.UUID        `json:"agent_id"`
	SecretType     string             `json:"secret_type"`
	EncryptedValue []byte             `json:"encrypted_value"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

type Command struct {
	ID           pgtype.UUID        `json:"id"`
	AgentID      pgtype.UUID        `json:"agent_id"`
	CommandType  string             `json:"command_type"`
	Payload      []byte             `json:"payload"`
	Status       string             `json:"status"`
	Priority     pgtype.Int4        `json:"priority"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
	ExecutedAt   pgtype.Timestamptz `json:"executed_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	Result       []byte             `json:"result"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type CommandHistory struct {
	ID           pgtype.UUID        `json:"id"`
	CommandID    pgtype.UUID        `json:"command_id"`
	AgentID      pgtype.UUID        `json:"agent_id"`
	Status       string             `json:"status"`
	Output       []byte             `json:"output"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	RecordedAt   pgtype.Timestamptz `json:"recorded_at"`
}
