// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAgentToGroup = `-- name: AddAgentToGroup :exec
INSERT INTO agent_group_members (agent_id, group_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddAgentToGroupParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	GroupID pgtype.UUID `json:"group_id"`
}

// Add agent to group
func (q *Queries) AddAgentToGroup(ctx context.Context, arg AddAgentToGroupParams) error {
	_, err := q.db.Exec(ctx, addAgentToGroup, arg.AgentID, arg.GroupID)
	return err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (
    agent_key_hash, name, hostname, ip_address, os_type, os_version,
    arch, version, capabilities, status, organization_id, tags, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, agent_key_hash, name, hostname, ip_address, os_type, os_version, arch, version, capabilities, status, last_heartbeat, registered_at, updated_at, metadata, organization_id, tags
`

type CreateAgentParams struct {
	AgentKeyHash   string      `json:"agent_key_hash"`
	Name           string      `json:"name"`
	Hostname       pgtype.Text `json:"hostname"`
	IpAddress      *netip.Addr `json:"ip_address"`
	OsType         string      `json:"os_type"`
	OsVersion      pgtype.Text `json:"os_version"`
	Arch           pgtype.Text `json:"arch"`
	Version        string      `json:"version"`
	Capabilities   []byte      `json:"capabilities"`
	Status         string      `json:"status"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Tags           []string    `json:"tags"`
	Metadata       []byte      `json:"metadata"`
}

// Register a new agent
func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.AgentKeyHash,
		arg.Name,
		arg.Hostname,
		arg.IpAddress,
		arg.OsType,
		arg.OsVersion,
		arg.Arch,
		arg.Version,
		arg.Capabilities,
		arg.Status,
		arg.OrganizationID,
		arg.Tags,
		arg.Metadata,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.AgentKeyHash,
		&i.Name,
		&i.Hostname,
		&i.IpAddress,
		&i.OsType,
		&i.OsVersion,
		&i.Arch,
		&i.Version,
		&i.Capabilities,
		&i.Status,
		&i.LastHeartbeat,
		&i.RegisteredAt,
		&i.UpdatedAt,
		&i.Metadata,
		&i.OrganizationID,
		&i.Tags,
	)
	return i, err
}

const createAgentConfig = `-- name: CreateAgentConfig :one

INSERT INTO agent_configs (agent_id, config_key, config_value, is_active)
VALUES ($1, $2, $3, $4)
ON CONFLICT (agent_id, config_key, is_active)
DO UPDATE SET config_value = $3, version = agent_configs.version + 1, updated_at = NOW()
RETURNING id, agent_id, config_key, config_value, version, is_active, created_at, updated_at
`

type CreateAgentConfigParams struct {
	AgentID     pgtype.UUID `json:"agent_id"`
	ConfigKey   string      `json:"config_key"`
	ConfigValue []byte      `json:"config_value"`
	IsActive    pgtype.Bool `json:"is_active"`
}

// =============================================================================
// Configuration Queries
// =============================================================================
// Create or update agent configuration
func (q *Queries) CreateAgentConfig(ctx context.Context, arg CreateAgentConfigParams) (AgentConfig, error) {
	row := q.db.QueryRow(ctx, createAgentConfig,
		arg.AgentID,
		arg.ConfigKey,
		arg.ConfigValue,
		arg.IsActive,
	)
	var i AgentConfig
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ConfigKey,
		&i.ConfigValue,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAgentData = `-- name: CreateAgentData :one

INSERT INTO agent_data (agent_id, data_type, payload, organization_id, tags, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, agent_id, data_type, payload, collected_at, processed_at, organization_id, tags, metadata
`

type CreateAgentDataParams struct {
	AgentID        pgtype.UUID `json:"agent_id"`
	DataType       string      `json:"data_type"`
	Payload        []byte      `json:"payload"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Tags           []string    `json:"tags"`
	Metadata       []byte      `json:"metadata"`
}

// =============================================================================
// Agent Data Queries
// =============================================================================
// Store collected data from agent
func (q *Queries) CreateAgentData(ctx context.Context, arg CreateAgentDataParams) (AgentDatum, error) {
	row := q.db.QueryRow(ctx, createAgentData,
		arg.AgentID,
		arg.DataType,
		arg.Payload,
		arg.OrganizationID,
		arg.Tags,
		arg.Metadata,
	)
	var i AgentDatum
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.DataType,
		&i.Payload,
		&i.CollectedAt,
		&i.ProcessedAt,
		&i.OrganizationID,
		&i.Tags,
		&i.Metadata,
	)
	return i, err
}

const createAgentGroup = `-- name: CreateAgentGroup :one

INSERT INTO agent_groups (name, description, organization_id)
VALUES ($1, $2, $3)
RETURNING id, name, description, organization_id, created_at, updated_at
`

type CreateAgentGroupParams struct {
	Name           string      `json:"name"`
	Description    pgtype.Text `json:"description"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// =============================================================================
// Group Management Queries
// =============================================================================
// Create new agent group
func (q *Queries) CreateAgentGroup(ctx context.Context, arg CreateAgentGroupParams) (AgentGroup, error) {
	row := q.db.QueryRow(ctx, createAgentGroup, arg.Name, arg.Description, arg.OrganizationID)
	var i AgentGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAgentHealth = `-- name: CreateAgentHealth :one

INSERT INTO agent_health (
    agent_id, cpu_usage, memory_usage, disk_usage,
    network_in, network_out, processes_count, uptime_seconds
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, agent_id, cpu_usage, memory_usage, disk_usage, network_in, network_out, processes_count, uptime_seconds, recorded_at
`

type CreateAgentHealthParams struct {
	AgentID        pgtype.UUID    `json:"agent_id"`
	CpuUsage       pgtype.Numeric `json:"cpu_usage"`
	MemoryUsage    pgtype.Numeric `json:"memory_usage"`
	DiskUsage      pgtype.Numeric `json:"disk_usage"`
	NetworkIn      pgtype.Int8    `json:"network_in"`
	NetworkOut     pgtype.Int8    `json:"network_out"`
	ProcessesCount pgtype.Int4    `json:"processes_count"`
	UptimeSeconds  pgtype.Int8    `json:"uptime_seconds"`
}

// =============================================================================
// Health Monitoring Queries
// =============================================================================
// Store health metrics
func (q *Queries) CreateAgentHealth(ctx context.Context, arg CreateAgentHealthParams) (AgentHealth, error) {
	row := q.db.QueryRow(ctx, createAgentHealth,
		arg.AgentID,
		arg.CpuUsage,
		arg.MemoryUsage,
		arg.DiskUsage,
		arg.NetworkIn,
		arg.NetworkOut,
		arg.ProcessesCount,
		arg.UptimeSeconds,
	)
	var i AgentHealth
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.CpuUsage,
		&i.MemoryUsage,
		&i.DiskUsage,
		&i.NetworkIn,
		&i.NetworkOut,
		&i.ProcessesCount,
		&i.UptimeSeconds,
		&i.RecordedAt,
	)
	return i, err
}

const createAgentLog = `-- name: CreateAgentLog :exec

INSERT INTO agent_logs (agent_id, level, message, source, metadata)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAgentLogParams struct {
	AgentID  pgtype.UUID `json:"agent_id"`
	Level    string      `json:"level"`
	Message  string      `json:"message"`
	Source   pgtype.Text `json:"source"`
	Metadata []byte      `json:"metadata"`
}

// =============================================================================
// Logging Queries
// =============================================================================
// Store log entry from agent
func (q *Queries) CreateAgentLog(ctx context.Context, arg CreateAgentLogParams) error {
	_, err := q.db.Exec(ctx, createAgentLog,
		arg.AgentID,
		arg.Level,
		arg.Message,
		arg.Source,
		arg.Metadata,
	)
	return err
}

const createAgentSecret = `-- name: CreateAgentSecret :one

INSERT INTO agent_secrets (agent_id, secret_type, encrypted_value, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (agent_id, secret_type)
DO UPDATE SET encrypted_value = $3, expires_at = $4
RETURNING id, agent_id, secret_type, encrypted_value, created_at, expires_at
`

type CreateAgentSecretParams struct {
	AgentID        pgtype.UUID        `json:"agent_id"`
	SecretType     string             `json:"secret_type"`
	EncryptedValue []byte             `json:"encrypted_value"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

// =============================================================================
// Secrets Management Queries
// =============================================================================
// Store encrypted secret
func (q *Queries) CreateAgentSecret(ctx context.Context, arg CreateAgentSecretParams) (AgentSecret, error) {
	row := q.db.QueryRow(ctx, createAgentSecret,
		arg.AgentID,
		arg.SecretType,
		arg.EncryptedValue,
		arg.ExpiresAt,
	)
	var i AgentSecret
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.SecretType,
		&i.EncryptedValue,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createCommand = `-- name: CreateCommand :one

INSERT INTO commands (
    agent_id, command_type, payload, status, priority,
    scheduled_at, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, agent_id, command_type, payload, status, priority, scheduled_at, executed_at, completed_at, result, error_message, created_by, created_at, updated_at
`

type CreateCommandParams struct {
	AgentID     pgtype.UUID        `json:"agent_id"`
	CommandType string             `json:"command_type"`
	Payload     []byte             `json:"payload"`
	Status      string             `json:"status"`
	Priority    pgtype.Int4        `json:"priority"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
}

// =============================================================================
// Command Queries
// =============================================================================
// Queue a new command for execution
func (q *Queries) CreateCommand(ctx context.Context, arg CreateCommandParams) (Command, error) {
	row := q.db.QueryRow(ctx, createCommand,
		arg.AgentID,
		arg.CommandType,
		arg.Payload,
		arg.Status,
		arg.Priority,
		arg.ScheduledAt,
		arg.CreatedBy,
	)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.CommandType,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.ScheduledAt,
		&i.ExecutedAt,
		&i.CompletedAt,
		&i.Result,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCommandHistory = `-- name: CreateCommandHistory :exec
INSERT INTO command_history (command_id, agent_id, status, output, error_message)
VALUES ($1, $2, $3, $4, $5)
`

type CreateCommandHistoryParams struct {
	CommandID    pgtype.UUID `json:"command_id"`
	AgentID      pgtype.UUID `json:"agent_id"`
	Status       string      `json:"status"`
	Output       []byte      `json:"output"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

// Record command history entry
func (q *Queries) CreateCommandHistory(ctx context.Context, arg CreateCommandHistoryParams) error {
	_, err := q.db.Exec(ctx, createCommandHistory,
		arg.CommandID,
		arg.AgentID,
		arg.Status,
		arg.Output,
		arg.ErrorMessage,
	)
	return err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = $1
`

// Permanently remove agent
func (q *Queries) DeleteAgent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgent, id)
	return err
}

const getAgentByID = `-- name: GetAgentByID :one


SELECT id, agent_key_hash, name, hostname, ip_address, os_type, os_version, arch, version, capabilities, status, last_heartbeat, registered_at, updated_at, metadata, organization_id, tags FROM agents WHERE id = $1
`

// =============================================================================
// File: query.sql
// Purpose: SQL queries for VORT agent system database operations
// Created: 2026-02-15
// =============================================================================
// This file contains named SQL queries for all VORT agent system operations.
// These queries are used with sqlc or similar tools to generate type-safe Go code.
// =============================================================================
// =============================================================================
// Agent Queries
// =============================================================================
// Retrieve a single agent by UUID
func (q *Queries) GetAgentByID(ctx context.Context, id pgtype.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByID, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.AgentKeyHash,
		&i.Name,
		&i.Hostname,
		&i.IpAddress,
		&i.OsType,
		&i.OsVersion,
		&i.Arch,
		&i.Version,
		&i.Capabilities,
		&i.Status,
		&i.LastHeartbeat,
		&i.RegisteredAt,
		&i.UpdatedAt,
		&i.Metadata,
		&i.OrganizationID,
		&i.Tags,
	)
	return i, err
}

const getAgentByKeyHash = `-- name: GetAgentByKeyHash :one
SELECT id, agent_key_hash, name, hostname, ip_address, os_type, os_version, arch, version, capabilities, status, last_heartbeat, registered_at, updated_at, metadata, organization_id, tags FROM agents WHERE agent_key_hash = $1
`

// Retrieve agent by authentication key hash
func (q *Queries) GetAgentByKeyHash(ctx context.Context, agentKeyHash string) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByKeyHash, agentKeyHash)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.AgentKeyHash,
		&i.Name,
		&i.Hostname,
		&i.IpAddress,
		&i.OsType,
		&i.OsVersion,
		&i.Arch,
		&i.Version,
		&i.Capabilities,
		&i.Status,
		&i.LastHeartbeat,
		&i.RegisteredAt,
		&i.UpdatedAt,
		&i.Metadata,
		&i.OrganizationID,
		&i.Tags,
	)
	return i, err
}

const getAgentConfig = `-- name: GetAgentConfig :one
SELECT id, agent_id, config_key, config_value, version, is_active, created_at, updated_at FROM agent_configs
WHERE agent_id = $1 AND config_key = $2 AND is_active = true
`

type GetAgentConfigParams struct {
	AgentID   pgtype.UUID `json:"agent_id"`
	ConfigKey string      `json:"config_key"`
}

// Retrieve active configuration value
func (q *Queries) GetAgentConfig(ctx context.Context, arg GetAgentConfigParams) (AgentConfig, error) {
	row := q.db.QueryRow(ctx, getAgentConfig, arg.AgentID, arg.ConfigKey)
	var i AgentConfig
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ConfigKey,
		&i.ConfigValue,
		&i.Version,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentGroups = `-- name: GetAgentGroups :many
SELECT ag.id, ag.name, ag.description, ag.organization_id, ag.created_at, ag.updated_at FROM agent_groups ag
JOIN agent_group_members agm ON ag.id = agm.group_id
WHERE agm.agent_id = $1
`

// Get groups for an agent
func (q *Queries) GetAgentGroups(ctx context.Context, agentID pgtype.UUID) ([]AgentGroup, error) {
	rows, err := q.db.Query(ctx, getAgentGroups, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentGroup
	for rows.Next() {
		var i AgentGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAgentSecret = `-- name: GetAgentSecret :one
SELECT id, agent_id, secret_type, encrypted_value, created_at, expires_at FROM agent_secrets
WHERE agent_id = $1 AND secret_type = $2
  AND (expires_at IS NULL OR expires_at > NOW())
`

type GetAgentSecretParams struct {
	AgentID    pgtype.UUID `json:"agent_id"`
	SecretType string      `json:"secret_type"`
}

// Retrieve active secret
func (q *Queries) GetAgentSecret(ctx context.Context, arg GetAgentSecretParams) (AgentSecret, error) {
	row := q.db.QueryRow(ctx, getAgentSecret, arg.AgentID, arg.SecretType)
	var i AgentSecret
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.SecretType,
		&i.EncryptedValue,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getAgentStats = `-- name: GetAgentStats :one

SELECT
    COUNT(*) FILTER (WHERE status = 'active') as active_count,
    COUNT(*) FILTER (WHERE status = 'inactive') as inactive_count,
    COUNT(*) FILTER (WHERE status = 'disconnected') as disconnected_count,
    COUNT(*) as total_count
FROM agents
WHERE organization_id = $1
`

type GetAgentStatsRow struct {
	ActiveCount       int64 `json:"active_count"`
	InactiveCount     int64 `json:"inactive_count"`
	DisconnectedCount int64 `json:"disconnected_count"`
	TotalCount        int64 `json:"total_count"`
}

// =============================================================================
// Statistics Queries
// =============================================================================
// Get agent count by status for organization
func (q *Queries) GetAgentStats(ctx context.Context, organizationID pgtype.UUID) (GetAgentStatsRow, error) {
	row := q.db.QueryRow(ctx, getAgentStats, organizationID)
	var i GetAgentStatsRow
	err := row.Scan(
		&i.ActiveCount,
		&i.InactiveCount,
		&i.DisconnectedCount,
		&i.TotalCount,
	)
	return i, err
}

const getAgentsByGroup = `-- name: GetAgentsByGroup :many
SELECT a.id, a.agent_key_hash, a.name, a.hostname, a.ip_address, a.os_type, a.os_version, a.arch, a.version, a.capabilities, a.status, a.last_heartbeat, a.registered_at, a.updated_at, a.metadata, a.organization_id, a.tags FROM agents a
JOIN agent_group_members agm ON a.id = agm.agent_id
WHERE agm.group_id = $1
`

// List agents in a group
func (q *Queries) GetAgentsByGroup(ctx context.Context, groupID pgtype.UUID) ([]Agent, error) {
	rows, err := q.db.Query(ctx, getAgentsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.AgentKeyHash,
			&i.Name,
			&i.Hostname,
			&i.IpAddress,
			&i.OsType,
			&i.OsVersion,
			&i.Arch,
			&i.Version,
			&i.Capabilities,
			&i.Status,
			&i.LastHeartbeat,
			&i.RegisteredAt,
			&i.UpdatedAt,
			&i.Metadata,
			&i.OrganizationID,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommand = `-- name: GetCommand :one
SELECT id, agent_id, command_type, payload, status, priority, scheduled_at, executed_at, completed_at, result, error_message, created_by, created_at, updated_at FROM commands WHERE id = $1
`

// Retrieve command by ID
func (q *Queries) GetCommand(ctx context.Context, id pgtype.UUID) (Command, error) {
	row := q.db.QueryRow(ctx, getCommand, id)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.CommandType,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.ScheduledAt,
		&i.ExecutedAt,
		&i.CompletedAt,
		&i.Result,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestHealth = `-- name: GetLatestHealth :one
SELECT id, agent_id, cpu_usage, memory_usage, disk_usage, network_in, network_out, processes_count, uptime_seconds, recorded_at FROM agent_health
WHERE agent_id = $1
ORDER BY recorded_at DESC
LIMIT 1
`

// Get most recent health data
func (q *Queries) GetLatestHealth(ctx context.Context, agentID pgtype.UUID) (AgentHealth, error) {
	row := q.db.QueryRow(ctx, getLatestHealth, agentID)
	var i AgentHealth
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.CpuUsage,
		&i.MemoryUsage,
		&i.DiskUsage,
		&i.NetworkIn,
		&i.NetworkOut,
		&i.ProcessesCount,
		&i.UptimeSeconds,
		&i.RecordedAt,
	)
	return i, err
}

const getPendingCommands = `-- name: GetPendingCommands :many
SELECT id, agent_id, command_type, payload, status, priority, scheduled_at, executed_at, completed_at, result, error_message, created_by, created_at, updated_at FROM commands
WHERE agent_id = $1
  AND status IN ('pending', 'dispatched')
  AND (scheduled_at IS NULL OR scheduled_at <= NOW())
ORDER BY priority DESC, created_at ASC
LIMIT $2
`

type GetPendingCommandsParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Limit   int32       `json:"limit"`
}

// Fetch pending commands for an agent
func (q *Queries) GetPendingCommands(ctx context.Context, arg GetPendingCommandsParams) ([]Command, error) {
	rows, err := q.db.Query(ctx, getPendingCommands, arg.AgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Command
	for rows.Next() {
		var i Command
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.CommandType,
			&i.Payload,
			&i.Status,
			&i.Priority,
			&i.ScheduledAt,
			&i.ExecutedAt,
			&i.CompletedAt,
			&i.Result,
			&i.ErrorMessage,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentConfigs = `-- name: ListAgentConfigs :many
SELECT id, agent_id, config_key, config_value, version, is_active, created_at, updated_at FROM agent_configs
WHERE agent_id = $1 AND is_active = true
ORDER BY config_key
`

// Get all active configurations
func (q *Queries) ListAgentConfigs(ctx context.Context, agentID pgtype.UUID) ([]AgentConfig, error) {
	rows, err := q.db.Query(ctx, listAgentConfigs, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentConfig
	for rows.Next() {
		var i AgentConfig
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.ConfigKey,
			&i.ConfigValue,
			&i.Version,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentData = `-- name: ListAgentData :many
SELECT id, agent_id, data_type, payload, collected_at, processed_at, organization_id, tags, metadata FROM agent_data
WHERE agent_id = $1
  AND ($2::varchar IS NULL OR data_type = $2)
ORDER BY collected_at DESC
LIMIT $3 OFFSET $4
`

type ListAgentDataParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Column2 string      `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

// Query collected agent data
func (q *Queries) ListAgentData(ctx context.Context, arg ListAgentDataParams) ([]AgentDatum, error) {
	rows, err := q.db.Query(ctx, listAgentData,
		arg.AgentID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentDatum
	for rows.Next() {
		var i AgentDatum
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.DataType,
			&i.Payload,
			&i.CollectedAt,
			&i.ProcessedAt,
			&i.OrganizationID,
			&i.Tags,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentHealth = `-- name: ListAgentHealth :many
SELECT id, agent_id, cpu_usage, memory_usage, disk_usage, network_in, network_out, processes_count, uptime_seconds, recorded_at FROM agent_health
WHERE agent_id = $1
ORDER BY recorded_at DESC
LIMIT $2
`

type ListAgentHealthParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Limit   int32       `json:"limit"`
}

// Get health history
func (q *Queries) ListAgentHealth(ctx context.Context, arg ListAgentHealthParams) ([]AgentHealth, error) {
	rows, err := q.db.Query(ctx, listAgentHealth, arg.AgentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentHealth
	for rows.Next() {
		var i AgentHealth
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.CpuUsage,
			&i.MemoryUsage,
			&i.DiskUsage,
			&i.NetworkIn,
			&i.NetworkOut,
			&i.ProcessesCount,
			&i.UptimeSeconds,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentLogs = `-- name: ListAgentLogs :many
SELECT id, agent_id, level, message, source, metadata, recorded_at FROM agent_logs
WHERE agent_id = $1
  AND ($2::varchar IS NULL OR level = $2)
ORDER BY recorded_at DESC
LIMIT $3 OFFSET $4
`

type ListAgentLogsParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Column2 string      `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

// Query agent logs
func (q *Queries) ListAgentLogs(ctx context.Context, arg ListAgentLogsParams) ([]AgentLog, error) {
	rows, err := q.db.Query(ctx, listAgentLogs,
		arg.AgentID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentLog
	for rows.Next() {
		var i AgentLog
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Level,
			&i.Message,
			&i.Source,
			&i.Metadata,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgents = `-- name: ListAgents :many
SELECT id, agent_key_hash, name, hostname, ip_address, os_type, os_version, arch, version, capabilities, status, last_heartbeat, registered_at, updated_at, metadata, organization_id, tags FROM agents
WHERE ($1::uuid IS NULL OR organization_id = $1)
  AND ($2::varchar IS NULL OR status = $2)
ORDER BY registered_at DESC
LIMIT $3 OFFSET $4
`

type ListAgentsParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 string      `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

// List agents with optional filtering
func (q *Queries) ListAgents(ctx context.Context, arg ListAgentsParams) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgents,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.AgentKeyHash,
			&i.Name,
			&i.Hostname,
			&i.IpAddress,
			&i.OsType,
			&i.OsVersion,
			&i.Arch,
			&i.Version,
			&i.Capabilities,
			&i.Status,
			&i.LastHeartbeat,
			&i.RegisteredAt,
			&i.UpdatedAt,
			&i.Metadata,
			&i.OrganizationID,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommands = `-- name: ListCommands :many
SELECT id, agent_id, command_type, payload, status, priority, scheduled_at, executed_at, completed_at, result, error_message, created_by, created_at, updated_at FROM commands
WHERE agent_id = $1
  AND ($2::varchar IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListCommandsParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Column2 string      `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

// List commands for an agent
func (q *Queries) ListCommands(ctx context.Context, arg ListCommandsParams) ([]Command, error) {
	rows, err := q.db.Query(ctx, listCommands,
		arg.AgentID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Command
	for rows.Next() {
		var i Command
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.CommandType,
			&i.Payload,
			&i.Status,
			&i.Priority,
			&i.ScheduledAt,
			&i.ExecutedAt,
			&i.CompletedAt,
			&i.Result,
			&i.ErrorMessage,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAgentFromGroup = `-- name: RemoveAgentFromGroup :exec
DELETE FROM agent_group_members WHERE agent_id = $1 AND group_id = $2
`

type RemoveAgentFromGroupParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	GroupID pgtype.UUID `json:"group_id"`
}

// Remove agent from group
func (q *Queries) RemoveAgentFromGroup(ctx context.Context, arg RemoveAgentFromGroupParams) error {
	_, err := q.db.Exec(ctx, removeAgentFromGroup, arg.AgentID, arg.GroupID)
	return err
}

const updateAgentHeartbeat = `-- name: UpdateAgentHeartbeat :one
UPDATE agents
SET last_heartbeat = NOW(), status = 'active', updated_at = NOW()
WHERE id = $1
RETURNING id, agent_key_hash, name, hostname, ip_address, os_type, os_version, arch, version, capabilities, status, last_heartbeat, registered_at, updated_at, metadata, organization_id, tags
`

// Record agent heartbeat
func (q *Queries) UpdateAgentHeartbeat(ctx context.Context, id pgtype.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgentHeartbeat, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.AgentKeyHash,
		&i.Name,
		&i.Hostname,
		&i.IpAddress,
		&i.OsType,
		&i.OsVersion,
		&i.Arch,
		&i.Version,
		&i.Capabilities,
		&i.Status,
		&i.LastHeartbeat,
		&i.RegisteredAt,
		&i.UpdatedAt,
		&i.Metadata,
		&i.OrganizationID,
		&i.Tags,
	)
	return i, err
}

const updateAgentStatus = `-- name: UpdateAgentStatus :one
UPDATE agents
SET status = $2, last_heartbeat = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, agent_key_hash, name, hostname, ip_address, os_type, os_version, arch, version, capabilities, status, last_heartbeat, registered_at, updated_at, metadata, organization_id, tags
`

type UpdateAgentStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

// Update agent status
func (q *Queries) UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgentStatus, arg.ID, arg.Status)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.AgentKeyHash,
		&i.Name,
		&i.Hostname,
		&i.IpAddress,
		&i.OsType,
		&i.OsVersion,
		&i.Arch,
		&i.Version,
		&i.Capabilities,
		&i.Status,
		&i.LastHeartbeat,
		&i.RegisteredAt,
		&i.UpdatedAt,
		&i.Metadata,
		&i.OrganizationID,
		&i.Tags,
	)
	return i, err
}

const updateCommandStatus = `-- name: UpdateCommandStatus :one
UPDATE commands
SET status = $2,
    executed_at = CASE WHEN $2 = 'running' THEN NOW() ELSE executed_at END,
    completed_at = CASE WHEN $2 IN ('completed', 'failed', 'cancelled', 'timeout') THEN NOW() ELSE completed_at END,
    result = COALESCE($3, result),
    error_message = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, agent_id, command_type, payload, status, priority, scheduled_at, executed_at, completed_at, result, error_message, created_by, created_at, updated_at
`

type UpdateCommandStatusParams struct {
	ID           pgtype.UUID `json:"id"`
	Status       string      `json:"status"`
	Result       []byte      `json:"result"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

// Update command execution status
func (q *Queries) UpdateCommandStatus(ctx context.Context, arg UpdateCommandStatusParams) (Command, error) {
	row := q.db.QueryRow(ctx, updateCommandStatus,
		arg.ID,
		arg.Status,
		arg.Result,
		arg.ErrorMessage,
	)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.CommandType,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.ScheduledAt,
		&i.ExecutedAt,
		&i.CompletedAt,
		&i.Result,
		&i.ErrorMessage,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
