// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Add agent to group
	AddAgentToGroup(ctx context.Context, arg AddAgentToGroupParams) error
	// Register a new agent
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	// =============================================================================
	// Configuration Queries
	// =============================================================================
	// Create or update agent configuration
	CreateAgentConfig(ctx context.Context, arg CreateAgentConfigParams) (AgentConfig, error)
	// =============================================================================
	// Agent Data Queries
	// =============================================================================
	// Store collected data from agent
	CreateAgentData(ctx context.Context, arg CreateAgentDataParams) (AgentDatum, error)
	// =============================================================================
	// Group Management Queries
	// =============================================================================
	// Create new agent group
	CreateAgentGroup(ctx context.Context, arg CreateAgentGroupParams) (AgentGroup, error)
	// =============================================================================
	// Health Monitoring Queries
	// =============================================================================
	// Store health metrics
	CreateAgentHealth(ctx context.Context, arg CreateAgentHealthParams) (AgentHealth, error)
	// =============================================================================
	// Logging Queries
	// =============================================================================
	// Store log entry from agent
	CreateAgentLog(ctx context.Context, arg CreateAgentLogParams) error
	// =============================================================================
	// Secrets Management Queries
	// =============================================================================
	// Store encrypted secret
	CreateAgentSecret(ctx context.Context, arg CreateAgentSecretParams) (AgentSecret, error)
	// =============================================================================
	// Command Queries
	// =============================================================================
	// Queue a new command for execution
	CreateCommand(ctx context.Context, arg CreateCommandParams) (Command, error)
	// Record command history entry
	CreateCommandHistory(ctx context.Context, arg CreateCommandHistoryParams) error
	// Permanently remove agent
	DeleteAgent(ctx context.Context, id pgtype.UUID) error
	// =============================================================================
	// File: query.sql
	// Purpose: SQL queries for VORT agent system database operations
	// Created: 2026-02-15
	// =============================================================================
	// This file contains named SQL queries for all VORT agent system operations.
	// These queries are used with sqlc or similar tools to generate type-safe Go code.
	// =============================================================================
	// =============================================================================
	// Agent Queries
	// =============================================================================
	// Retrieve a single agent by UUID
	GetAgentByID(ctx context.Context, id pgtype.UUID) (Agent, error)
	// Retrieve agent by authentication key hash
	GetAgentByKeyHash(ctx context.Context, agentKeyHash string) (Agent, error)
	// Retrieve active configuration value
	GetAgentConfig(ctx context.Context, arg GetAgentConfigParams) (AgentConfig, error)
	// Get groups for an agent
	GetAgentGroups(ctx context.Context, agentID pgtype.UUID) ([]AgentGroup, error)
	// Retrieve active secret
	GetAgentSecret(ctx context.Context, arg GetAgentSecretParams) (AgentSecret, error)
	// =============================================================================
	// Statistics Queries
	// =============================================================================
	// Get agent count by status for organization
	GetAgentStats(ctx context.Context, organizationID pgtype.UUID) (GetAgentStatsRow, error)
	// List agents in a group
	GetAgentsByGroup(ctx context.Context, groupID pgtype.UUID) ([]Agent, error)
	// Retrieve command by ID
	GetCommand(ctx context.Context, id pgtype.UUID) (Command, error)
	// Get most recent health data
	GetLatestHealth(ctx context.Context, agentID pgtype.UUID) (AgentHealth, error)
	// Fetch pending commands for an agent
	GetPendingCommands(ctx context.Context, arg GetPendingCommandsParams) ([]Command, error)
	// Get all active configurations
	ListAgentConfigs(ctx context.Context, agentID pgtype.UUID) ([]AgentConfig, error)
	// Query collected agent data
	ListAgentData(ctx context.Context, arg ListAgentDataParams) ([]AgentDatum, error)
	// Get health history
	ListAgentHealth(ctx context.Context, arg ListAgentHealthParams) ([]AgentHealth, error)
	// Query agent logs
	ListAgentLogs(ctx context.Context, arg ListAgentLogsParams) ([]AgentLog, error)
	// List agents with optional filtering
	ListAgents(ctx context.Context, arg ListAgentsParams) ([]Agent, error)
	// List commands for an agent
	ListCommands(ctx context.Context, arg ListCommandsParams) ([]Command, error)
	// Remove agent from group
	RemoveAgentFromGroup(ctx context.Context, arg RemoveAgentFromGroupParams) error
	// Record agent heartbeat
	UpdateAgentHeartbeat(ctx context.Context, id pgtype.UUID) (Agent, error)
	// Update agent status
	UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) (Agent, error)
	// Update command execution status
	UpdateCommandStatus(ctx context.Context, arg UpdateCommandStatusParams) (Command, error)
}

var _ Querier = (*Queries)(nil)
