// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_logs
WHERE ($1::text IS NULL OR user_id = $1)
`

func (q *Queries) CountAuditLogs(ctx context.Context, userID pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
    user_id, username, action, resource_type, resource_id, details
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, username, action, resource_type, resource_id, details, created_at
`

type CreateAuditLogParams struct {
	UserID       string `json:"user_id"`
	Username     string `json:"username"`
	Action       string `json:"action"`
	ResourceType string `json:"resource_type"`
	ResourceID   string `json:"resource_id"`
	Details      []byte `json:"details"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.UserID,
		arg.Username,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Details,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const getSystemConfig = `-- name: GetSystemConfig :one
SELECT key, value, updated_at FROM system_config
WHERE key = $1
`

func (q *Queries) GetSystemConfig(ctx context.Context, key string) (SystemConfig, error) {
	row := q.db.QueryRow(ctx, getSystemConfig, key)
	var i SystemConfig
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, user_id, username, action, resource_type, resource_id, details, created_at FROM audit_logs
WHERE 
    ($3::text IS NULL OR user_id = $3)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	UserID pgtype.Text `json:"user_id"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Limit, arg.Offset, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSystemConfig = `-- name: SetSystemConfig :one
INSERT INTO system_config (key, value, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (key) DO UPDATE
SET value = $2, updated_at = NOW()
RETURNING key, value, updated_at
`

type SetSystemConfigParams struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

func (q *Queries) SetSystemConfig(ctx context.Context, arg SetSystemConfigParams) (SystemConfig, error) {
	row := q.db.QueryRow(ctx, setSystemConfig, arg.Key, arg.Value)
	var i SystemConfig
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}
