// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAuditLogs(ctx context.Context, userID pgtype.Text) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	GetSystemConfig(ctx context.Context, key string) (SystemConfig, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	SetSystemConfig(ctx context.Context, arg SetSystemConfigParams) (SystemConfig, error)
}

var _ Querier = (*Queries)(nil)
