// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Queries for probe
	GetProbeExample(ctx context.Context) (ProbeExample, error)
}

var _ Querier = (*Queries)(nil)
