// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getSonarExample = `-- name: GetSonarExample :one

SELECT id, created_at FROM sonar_example LIMIT 1
`

// Queries for sonar
func (q *Queries) GetSonarExample(ctx context.Context) (SonarExample, error) {
	row := q.db.QueryRow(ctx, getSonarExample)
	var i SonarExample
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
