// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getShieldExample = `-- name: GetShieldExample :one

SELECT id, created_at FROM shield_example LIMIT 1
`

// Queries for shield
func (q *Queries) GetShieldExample(ctx context.Context) (ShieldExample, error) {
	row := q.db.QueryRow(ctx, getShieldExample)
	var i ShieldExample
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
